frameworkVersion: "4"

service: core

provider:
    name: aws
    runtime: nodejs20.x
    httpApi:
        disableDefaultEndpoint: true

functions:
    getYear:
        handler: handler.getYear
        events:
            - http:
                  path: core/year
                  method: get
                  cors: true

plugins:
    - serverless-offline

custom:
    serverless-offline:
        lambdaPath: ./dist
        noPrependStageInUrl: true
        servicePath: ${__dirname}
