
frameworkVersion: "4"

service: teams

provider:
    name: aws
    runtime: nodejs20.x
    httpApi:
        disableDefaultEndpoint: true

functions:
    getYear:
        handler: handler.test
        events:
            - http:
                  path: teams/test
                  method: get
                  cors: true

plugins:
    - serverless-offline

custom:
    serverless-offline:
        lambdaPath: ./dist
        noPrependStageInUrl: true
        servicePath: ${__dirname}

