
frameworkVersion: "4"

service: media

provider:
    name: aws
    runtime: nodejs20.x
    httpApi:
        disableDefaultEndpoint: true

functions:
    getYear:
        handler: handler.test
        events:
            - http:
                  path: media/ping
                  method: get
                  cors: true
    getPhoto:
        handler: handler.getPhoto
        events:
            - http:
                path: media/photo/{filename}
                method: get
                cors: true
    getGallery:
        handler: handler.getGallery
        events:
            - http:
                path: media/gallery
                method: get
                cors: true

plugins:
    - serverless-offline

custom:
    serverless-offline:
        lambdaPath: ./dist
        noPrependStageInUrl: true
        servicePath: ${__dirname}

